### ISSUE TITLE
 actividad 2 infografía Castro Rodríguez  Betsabe

### ISSUE THREAD

**Issue by ARICELCASTRO1999** [SistemasTecTlaxiaco/actividad-2-infografia-ARICELCASTRO1999#1]
[ilovepdf_pages-to-jpg.zip](https://github.com/SistemasTecTlaxiaco/actividad-2-infografia-ARICELCASTRO1999/files/9465313/ilovepdf_pages-to-jpg.zip)

**Comment by 11042002** [comment]
Tu calificación es de: 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
