### ISSUE TITLE
Actividad 2, infografia

### ISSUE THREAD

**Issue by Abisaylopez** [SistemasTecTlaxiaco/actividad-2-infografia-ARICELCASTRO1999#2]
[INFOGRAFIA .pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-infografia-ARICELCASTRO1999/files/9526240/INFOGRAFIA.pdf)

Abisay López Mendoza 1bs

**Comment by josealfredo79** [comment]
Falta la calificacion

**Comment by gilbertovelasco1** [comment]
15 %

**Comment by josealfredo79** [comment]
Esto no es una infografia...por favor de realizar nuevamente...

**Comment by josealfredo79** [comment]
@gilbertovelasco1 favor de evaluar una infografia como marca el trabjo..por favor

**Comment by PedroGarcia11439** [comment]
14% Seria la calificación basado en la rubrica

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
